export const ERR_MSG = {
  NAME_IS_REQUIRED: "Name is required and should be at least 3 characters long",
  ID_IS_REQUIRED: "ID is required and should be a positive number",
  PROJECT_ID_IS_REQUIRED: "Project ID is required and should be a positive number",
  FILE_ID_IS_REQUIRED: "Atleast one File ID is required and should be a positive number",
  FILE_ID_LIMIT_EXCEEDED: "Atmost 10 File IDs are allowed",
  INVALID_JOB_STATUS: "Invalid job status, should be one of 'PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'",
  FILE_DOES_NOT_BELONG_TO_PROJECT: "One or more files do not belong to project",
  FAILED_TO_QUEUE_JOB: "Failed to queue job",
  NO_OUTPUT_FILE_CREATED: "No output file created",
  UNKNOWN_ERROR_IN_RUN: "Unknown error in worker run()",
  FAILED_TO_CREATE_FILE_IN_DB: "Failed to create file in db",
  FAILED_TO_LIST_FILES_FROM_DB: "Failed to list files from db",
  FAILED_TO_DELETE_FILE_FROM_DB: "Failed to delete file from db",
  FAILED_TO_GET_FILE_FROM_DB: "Failed to get file from db",
  FAILED_TO_CREATE_JOB_IN_DB: "Failed to create job in db",
  FAILED_TO_FIND_ACTIVE_JOBS_IN_DB: "Failed to find active jobs in db",
  FAILED_TO_FIND_JOBS_IN_DB: "Failed to find jobs in db",
  FAILED_TO_FIND_PENDING_JOBS_IN_DB: "Failed to find pending jobs in db",
  FAILED_TO_UPDATE_JOB_IN_DB: "Failed to update job in db",
  FAILED_TO_ADD_FILES_TO_JOB_IN_DB: "Failed to add files to job in db",
  FAILED_TO_GET_JOB_FILES_FROM_DB: "Failed to get job files from db",
  FAILED_TO_CREATE_PROJECT_IN_DB: "Failed to create project in db",
  NOT_FOUND_IN_DB: "Not found in db",
  NO_PROJECTS_FOUND_IN_DB: "No projects found in db",
  NO_FIELDS_PROVIDED_FOR_UPDATE: "No fields provided for update",
  PROJECT_NOT_UPDATED_OR_FOUND_IN_DB: "Project not updated or found in db",
  PROJECT_NOT_DELETED_OR_FOUND_IN_DB: "Project not deleted or found in db",
  NO_FILES: "No files",
  FILE_NOT_FOUND: "File not found",
};
